// Generated by CoffeeScript 1.4.0
(function() {
  var HOST, jserv;

  HOST = 'jack-herrington.vm.lithium.com:8080';

  this.NLPService = (function() {

    function NLPService() {
      var _this = this;
      this.running = {};
      window.setTimeout(function() {
        return _this.update();
      }, 200);
    }

    NLPService.prototype.update = function() {
      var key,
        _this = this;
      for (key in this.running) {
        this.status(key, function(data) {
          if (data.status === 'complete') {
            return _this.get(key, function(data) {
              _this.running[key](data);
              return delete _this.running[key];
            });
          }
        });
      }
      return window.setTimeout(function() {
        return _this.update();
      }, 200);
    };

    NLPService.prototype.process = function(text, callback, customer) {
      var cb,
        _this = this;
      if (customer == null) {
        customer = 1;
      }
      cb = callback;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/start",
        type: 'POST',
        data: {
          customer: customer,
          type: 'SINGLE',
          text: text,
          extra: null
        },
        success: function(data) {
          return _this.running[data.jobid] = callback;
        }
      });
    };

    NLPService.prototype.status = function(job_id, callback) {
      var _this = this;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/status/" + job_id,
        type: 'GET',
        success: function(data) {
          return callback(data);
        }
      });
    };

    NLPService.prototype.get = function(job_id, callback) {
      var _this = this;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/get/" + job_id,
        type: 'GET',
        success: function(data) {
          return callback(data);
        }
      });
    };

    return NLPService;

  })();

  jserv = new this.NLPService();

  jserv.process('I\'ve been trying to figure out what kind of lip makeup should I wear (i.e. lip stain, stick, gloss). Also, I want to find a suitable color for my very fair skin.  Most of the time when I wear lip stick it fades rather quickly, especially in the middle and then I\'m left with the color only around my outer lips. I also tend to like a little shine.  What should I use??', function(data) {
    return console.log(data);
  });

}).call(this);
