// Generated by CoffeeScript 1.4.0
(function() {
  var HOST, jserv;

  HOST = 'jack-herrington.vm.lithium.com:8080';

  this.NLPService = (function() {

    function NLPService() {
      var _this = this;
      this.running = {};
      this.queue = [];
      this.in_process = false;
      window.setTimeout(function() {
        return _this.update();
      }, 200);
    }

    NLPService.prototype.update_job = function(key) {
      var _this = this;
      return this.status(key, function(data) {
        if (data.status === 'complete') {
          return _this.get(key, function(data) {
            if (_this.running[key] != null) {
              _this.running[key](data);
              delete _this.running[key];
              _this.in_process = false;
              return _this.process_queue();
            }
          });
        }
      });
    };

    NLPService.prototype.update = function() {
      var key,
        _this = this;
      for (key in this.running) {
        this.update_job(key);
      }
      return window.setTimeout(function() {
        return _this.update();
      }, 200);
    };

    NLPService.prototype.process = function(text, callback, customer) {
      if (customer == null) {
        customer = 1;
      }
      this.queue.push({
        text: text,
        callback: callback,
        customer: customer
      });
      return this.process_queue();
    };

    NLPService.prototype.process_queue = function() {
      var job;
      if (this.in_process || this.queue.length === 0) {
        return;
      }
      job = this.queue.shift();
      return this.start_job(job.text, job.callback, job.customer);
    };

    NLPService.prototype.start_job = function(text, callback, customer) {
      var cb,
        _this = this;
      this.in_process = true;
      cb = callback;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/start",
        type: 'POST',
        data: {
          customer: customer,
          type: 'SINGLE',
          text: text,
          extra: null
        },
        success: function(data) {
          return _this.running[data.jobid] = callback;
        }
      });
    };

    NLPService.prototype.status = function(job_id, callback) {
      var _this = this;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/status/" + job_id,
        type: 'GET',
        success: function(data) {
          return callback(data);
        }
      });
    };

    NLPService.prototype.get = function(job_id, callback) {
      var _this = this;
      return $.ajax({
        url: "http://" + HOST + "/api/v1/jobs/get/" + job_id,
        type: 'GET',
        success: function(data) {
          return callback(data);
        }
      });
    };

    return NLPService;

  })();

  jserv = new this.NLPService();

}).call(this);
